<?xml version="1.0"?>
<package format="3">
  <name>coencoder</name>
  <version>1.2.0</version>
  <description>The coencoder package</description>
  <maintainer email="coscene@coscene.io">coscene</maintainer>
  <license>Apache License 2.0</license>

  <buildtool_depend condition="$ROS_VERSION == 1">catkin</buildtool_depend>
  <buildtool_depend condition="$ROS_VERSION == 2">ament_cmake</buildtool_depend>

  <depend condition="$ROS_VERSION == 1">roscpp</depend>
  <depend condition="$ROS_VERSION == 1">roslib</depend>

  <depend condition="$ROS_VERSION == 2">rclcpp</depend>

  <depend>sensor_msgs</depend>
<!--  <depend>coscene_msgs</depend>-->
  <depend>foxglove_msgs</depend>
  <depend>std_srvs</depend>
  <depend>image_transport</depend>
  <depend>OpenCV</depend>

  <!-- <exec_depend>libavformat-dev</exec_depend> -->
  <exec_depend>libavcodec-dev</exec_depend>
  <exec_depend>libavutil-dev</exec_depend>
  <!-- <exec_depend>libswscale-dev</exec_depend> -->

  <export>
    <build_type condition="$ROS_VERSION == 1">catkin</build_type>
    <build_type condition="$ROS_VERSION == 2">ament_cmake</build_type>
  </export>
</package>
